# system
server: server
device: cuda
seed: 0

# Logger
save_freq: 100
save_dir: results

# Molecule
molecule: alanine
start_state: c5
end_state: c7ax
direction: two-way

# Simulation
num_steps: 1000
timestep: 1
temperature: 300

# Sampling
force: False
num_samples: 8
bias_scale: 0.01
sigma: 0.05

# Training
num_rollouts: 2000
trains_per_rollout: 200
train_temperature: 600
log_z_lr: 0.01
log_z_optimizer: adam
log_z_scheduler: cosineannealwarmrestarts
mlp_lr: 0.0001
mlp_optimizer: adam
mlp_scheduler: cosineannealwarmrestarts
max_grad_norm: 10
buffer_size: 40