# System
type: train
server: server
device: cuda
seed: 0

# Logger
wandb: True
save_freq: 100
save_dir: results
molecule: alanine
project: tps-tune

# Sampling
state_state: c5
end_state: c7ax
num_steps: 500
bias_scale: 20
timestep: 1
sigma: 0.05
num_samples: 16
temperature: 300

# Training
num_rollouts: 5000
trains_per_rollout: 200
train_temperature: 600
log_z_lr: 0.01
log_z_optimizer: adam
log_z_scheduler: multistep
mlp_lr: 0.0001
mlp_optimizer: adam
mlp_scheduler: multistep
max_grad_norm: 10
buffer_size: 2048
force: False