# system:
molecule: alanine
project: tps-tune
seed: 0
type: train
device: cuda

# logger:
freq_rollout_csave: 20
server: server

# policy:
force: False
goal_conditioned: False

# molecule
bias_scale: 0.4
std: 0.05
start_std: 0.2
end_std: 0.1
hindsight: false
terminal_std: 0.05

# training:
loss: tb
learning_rate: 0.01
num_rollouts: 1000
trains_per_rollout: 2000
buffer_size: 100
max_grad_norm: 10
optimizer: sgd
scheduler: exp

# sampling:
start_states: c5
end_states: c7ax
num_steps: 2000
num_samples: 16
temperature: 0
